### ISSUE TITLE
uncaughtException during fury.parse

### ISSUE THREAD

**Issue by opichals** [apiaryio/fury-adapter-swagger#169]
`process.nextTick()` is used to schedule fury.parse() work and that can cause `uncaughtException`

Introduced in https://github.com/apiaryio/fury-adapter-swagger/pull/74

Exception detail (as seen in https://github.com/apiaryio/apiary/pull/5402#issuecomment-382554423):
```
Apr 19 00:33:35 apiary heroku/run.7802: Process exited with status 1 
Apr 19 00:33:35 apiary app/run.7802: /app/node_modules/fury-adapter-swagger/lib/parser.js:1361 
Apr 19 00:33:35 apiary app/run.7802:       var element = new Type(); 
Apr 19 00:33:35 apiary app/run.7802:                     ^ 
Apr 19 00:33:35 apiary app/run.7802: TypeError: Type is not a constructor 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.convertParameterToElement (/app/node_modules/fury-adapter-swagger/lib/parser.js:1361:21) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.<anonymous> (/app/node_modules/fury-adapter-swagger/lib/parser.js:1409:38) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.withPath (/app/node_modules/fury-adapter-swagger/lib/parser.js:324:39) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.convertParameterToElement (/app/node_modules/fury-adapter-swagger/lib/parser.js:1408:14) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.convertParameterToMember (/app/node_modules/fury-adapter-swagger/lib/parser.js:1441:30) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.<anonymous> (/app/node_modules/fury-adapter-swagger/lib/parser.js:1524:30) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.withPath (/app/node_modules/fury-adapter-swagger/lib/parser.js:324:39) 
Apr 19 00:33:35 apiary app/run.7802:     at /app/node_modules/fury-adapter-swagger/lib/parser.js:1520:17 
Apr 19 00:33:35 apiary app/run.7802:     at arrayEach (/app/node_modules/lodash/lodash.js:537:11) 
Apr 19 00:33:35 apiary app/run.7802:     at Function.forEach (/app/node_modules/lodash/lodash.js:9344:14) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.createHrefVariables (/app/node_modules/fury-adapter-swagger/lib/parser.js:1519:24) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.<anonymous> (/app/node_modules/fury-adapter-swagger/lib/parser.js:864:42) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.withPath (/app/node_modules/fury-adapter-swagger/lib/parser.js:324:39) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.handleSwaggerMethod (/app/node_modules/fury-adapter-swagger/lib/parser.js:806:12) 
Apr 19 00:33:35 apiary app/run.7802:     at /app/node_modules/fury-adapter-swagger/lib/parser.js:759:18 
Apr 19 00:33:35 apiary app/run.7802:     at /app/node_modules/lodash/lodash.js:4970:15 
Apr 19 00:33:35 apiary app/run.7802:     at baseForOwn (/app/node_modules/lodash/lodash.js:3020:24) 
Apr 19 00:33:35 apiary app/run.7802:     at /app/node_modules/lodash/lodash.js:4939:18 
Apr 19 00:33:35 apiary app/run.7802:     at Function.forEach (/app/node_modules/lodash/lodash.js:9344:14) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.<anonymous> (/app/node_modules/fury-adapter-swagger/lib/parser.js:758:26) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.withPath (/app/node_modules/fury-adapter-swagger/lib/parser.js:324:39) 
Apr 19 00:33:35 apiary app/run.7802:     at Parser.handleSwaggerPath (/app/node_modules/fury-adapter-swagger/lib/parser.js:704:12) 
Apr 19 00:33:35 apiary app/run.7802:     at /app/node_modules/fury-adapter-swagger/lib/parser.js:279:21 
Apr 19 00:33:35 apiary app/run.7802:     at _combinedTickCallback (internal/process/next_tick.js:73:7) 
Apr 19 00:33:35 apiary app/run.7802:     at process._tickCallback (internal/process/next_tick.js:104:9) 
Apr 19 00:33:35 apiary heroku/run.7802: State changed from up to complete 
```

**Comment by kylef** [comment]
I believe this exception was actually introduced in https://github.com/apiaryio/fury-adapter-swagger/pull/124. @opichals do you have an example Swagger document that can reproduce this one so we can see what is happening?

Seems that there is some type that is permitted and isn't in the list at https://github.com/apiaryio/fury-adapter-swagger/blob/06d8bbd0fc4eda9fe0079e81363dd6b2813e52c3/src/parser.js#L1159-L1175 and therefore Type becomes undefined. As far as I recall Swagger doesn't allow any other types than what is handled in that code block. Unless there is a bug in swagger-schema which is falsely allowing some other value to be there.

**Comment by kylef** [comment]
Actually, I think I fixed this in https://github.com/apiaryio/fury-adapter-swagger/pull/154 which made it into [fury-adapter-swagger 0.16.1](https://github.com/apiaryio/fury-adapter-swagger/releases/tag/v0.16.1). @opichals Which version of the adapter are you running?

**Comment by opichals** [comment]
@kylef I meant this https://github.com/apiaryio/fury-adapter-swagger/pull/74 introduced `nextTick` scheduling which would throw `uncaughtException` if anything goes wrong which are difficult to deal with in a consuming code.

It was run yesterday in production, so [v0.13.3](https://github.com/apiaryio/apiary/blob/2875b9557894f9c6d87633c756d186fcb248cc3b/npm-shrinkwrap.json#L7546).

I should be able to get the swagger document if https://github.com/apiaryio/apiary/pull/5404 gets merged without upgrading the fury toolchain as proposed in https://github.com/apiaryio/apiary/pull/5405 and I re-run the script (and if the document doesn't get updated by its users) .

**Comment by kylef** [comment]
We've removed the use of nextTick in https://github.com/apiaryio/api-elements.js/pull/140
