### ISSUE TITLE
Add recursive JSON Schema support

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/fury-adapter-swagger#45]
The following swagger document is crashing the module.

``` yaml
swagger: '2.0'
info:
  description: Sample API
  version: 1.0.0
  title: Sample API
host: 'example.com'
basePath: /v1
tags:
  - name: Recursion
    description: Lorem Ipsum
schemes:
  - https
paths:
  '/recursive':
    get:
      tags:
        - Recursion
      summary: Recursion test
      description: |-
        This is a test to show that there are issues with recursion
      parameters:
        - name: tag
          in: query
          description: 'Test 1 2'
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            "$ref": "#/definitions/category"
definitions:
  category:
    type: object
    properties:
      id:
        type: string
      categoryAsArray:
        type: array
        description: A list of categories
        items:
          "$ref": "#/definitions/category"
      categoryAsObject:
        type: object
        "$ref": "#/definitions/category"
    description: A category groups one or more categories
```

**Comment by kylef** [comment]
To add more information:

```
/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:1008
      var schemaAsset = new Asset(JSON.stringify(jsonSchema));
                                       ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Parser.createAssetFromJsonSchema (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:1008:40)
    at Parser.<anonymous> (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:697:40)
    at Parser.withPath (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:251:54)
    at Parser.withSlicedPath (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:303:21)
    at Parser.<anonymous> (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:696:35)
    at Parser.withPath (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:251:54)
    at Parser.<anonymous> (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:668:16)
    at Parser.withPath (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:251:54)
    at Parser.handleSwaggerExampleResponse (/usr/local/lib/node_modules/swagger2blueprint/node_modules/fury-adapter-swagger/lib/parser.js:641:12)
```

**Comment by pksunkara** [comment]
We are giving out a better error now.
